services:
  postgres:
    image: postgres:17

    container_name: sql-warehouse-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: shohan
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sql_warehouse

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: